Repository SeattleColleges/licton-springs-review-nextjs, pull requests merged in 2025-02, with the labels that each got.

#48 licton-springs-review-nextjs_17_homepage-minor-changes
  public/Early-Bloom-main.jpg
  src/app/layout.tsx
  src/app/page.tsx
  src/component/Footer.tsx
  src/component/Header.tsx
  src/component/Post.tsx
Labels: bug, Sprint 17

#56 NextConfgi Update
  next.config.ts
Labels: Sprint 17

#42 licton-springs-review-nextjs_17_Issue30_Added-Fiction-Page-with-Hello-World
  src/app/fiction/page.tsx
  src/component/Footer.tsx
  src/component/Header.tsx
  src/component/Navbar.tsx
  src/component/Post.tsx
Labels: enhancement, Sprint 17

#41 Poetry page hello world
  src/app/poetry/page.tsx
Labels: enhancement, Sprint 17

#53 licton-springs-review-nextjs_17_Issue52_Added-Jobs-Page-with-Hello-World
  src/app/jobs/page.tsx
  src/component/Footer.tsx
Labels: enhancement, Sprint 17

#44 licton-springs-review-nextjs_17_40_help-hello-world
  src/app/help/page.tsx
Labels: enhancement, Sprint 17

#50 licton-springs-review-nextjs_17_Issue32_Added-Arts-Page-with-Hello-World
  src/app/art/page.tsx
Labels: enhancement, Sprint 17

#51 licton-springs-review-nextjs_17_Issue33_Added-Archive-Page-with-Hello-World
  src/app/archives/page.tsx
Labels: enhancement, Sprint 17

#58 licton-springs-review-nextjs_18_57_submit-hello-world
  src/app/submit/page.tsx
  src/component/Navbar.tsx
Labels: enhancement, Sprint 18

#72 licton-springs-review-nextjs_19_Issue62-removal-of-home-page
  src/component/Navbar.tsx
Labels: Sprint 19
