Repository SeattleColleges/licton-springs-review-nextjs, pull requests merged in 2025-06, with the labels that each got.

#96 licton-springs-review-nextjs_24_handle-new-fiction-content
  src/app/fiction/page.tsx
  src/app/fiction/post/page.tsx
  src/component/SingleFictionPost.tsx
Labels: enhancement, Sprint 24

#100 Licton springs review nextjs 24 handle new essay content
  public/the_ledge_canyon.jpg
  public/the_ledge_hero_dog.jpg
  src/app/non-fiction/page.tsx
  src/app/non-fiction/post/page.tsx
  src/component/SingleNonfictionPost.tsx
Labels: enhancement, Sprint 24

#99 licton-springs-review-nextjs_24_98_fix-suspense-build-fail
  src/app/art/post/page.tsx
  src/app/fiction/post/page.tsx
  src/app/non-fiction/post/page.tsx
  src/app/poetry/post/page.tsx
Labels: bug

#113 licton-springs-review-nextjs_24_help-page-footer-bottom
  src/app/help/page.tsx
  src/app/layout.tsx
Labels: enhancement

#112 Added a link component to the header image
  src/component/Header.tsx
Labels: Sprint 24

#121 updating verbiage
  src/app/audio/page.tsx
Labels: enhancement

#117 licton-springs-nextjs_24_move-award-winners-to-top
  src/app/fiction/page.tsx
  src/app/non-fiction/page.tsx
  src/component/SingleFictionPost.tsx
  src/component/SingleNonfictionPost.tsx
Labels: enhancement, Sprint 24

#126 Fix: adjusted responsiveness on smaller devices
  src/app/globals.css
Labels: enhancement
