Repository SeattleColleges/licton-springs-review-nextjs, pull requests merged in 2025-03, with the labels that each got.

#73 licton-springs-review-nextjs_19_Issue67-add-logo-slogan
  src/app/globals.css
  src/component/Header.tsx
Labels: enhancement, Sprint 19

#71 licton-springs-review-nextjs_19_Issue63-social-media-links
  package-lock.json
  package.json
  src/app/globals.css
  src/component/Header.tsx
  src/component/SocialMediaLinks.tsx
Labels: enhancement

#87 Licton springs review nextjs 20 69 fetch multiple posts by category from wordpress
  src/app/art/page.tsx
  src/component/PostsByCategory.tsx
  src/fetch-category-posts.tsx
  src/fetch-wp-content.tsx
Labels: enhancement, Sprint 20

#82 licton-springs-review-nextjs_19_Issue66_image-upload-submission-page-research
  src/app/globals.css
  src/app/submit/page.tsx
Labels: enhancement, Sprint 19

#89 Licton-springs-review-nextjs-20-69-load-page-content-using-fetch-wordpress-api
  src/app/art/page.tsx
  src/app/art/post/page.tsx
  src/app/fiction/page.tsx
  src/app/fiction/post/page.tsx
  src/app/globals.css
  src/app/job/page.tsx
  src/app/non-fiction/page.tsx
  src/app/non-fiction/post/page.tsx
  src/app/poetry/page.tsx
  src/app/poetry/post/page.tsx
  src/app/submit/page.tsx
  src/component/Detail.tsx
  src/component/Footer.tsx
  src/component/Header.tsx
  src/component/PostsByCategory.tsx
  src/component/SchoolLogo.tsx
  src/component/styles/Detail.module.css
  src/fetch-wp-content.tsx
Labels: enhancement, Sprint 20

#90 licton-springs-review-nextjs_20_69_load-audio-page-content
  src/app/audio/page.tsx
  src/app/globals.css
Labels: enhancement, Sprint 20
