Repository SeattleColleges/licton-springs-review-nextjs, pull requests merged in 2025-01, with the labels that each got.

#18 licton-springs-review-nextjs_16_17_send_to_bottom
  post-issue-smartsheet.py
Labels: enhancement

#7 Licton Springs Review NextJS - Sprint 16 - Issue 4 - Create rough draft of home page
  src/app/homepage-designs/Rory-Desktop.png
  src/app/homepage-designs/Rory-Mobile.png
  src/app/page.tsx
Labels: Sprint 16

#9 licton-springs-review-nextjs-16-8-bug-typescript-import-error
  tsconfig.json
Labels: bug
